#!/usr/bin/env python3

import phase2_result
for vname, nice_name in phase2_result.__names.items():
	v, t = getattr(phase2_result, vname)
	if v.find("D18") != -1:
		#print(nice_name, v)
		if t[-1] == []:
			t = t[:-1]
		noro = False
		for brange, bdesc in t[1:]:
			if bdesc.strip().startswith("Reserved"):
				continue
			read_only = bdesc.strip().find("Read-only") != -1
			write_only = bdesc.strip().find("Write-only") != -1
			read_write = bdesc.strip().find("Read-write") != -1
			# The same register can have a conditional like foo ? Read-only : Read-write.
			#if read_only and (write_only or read_write):
			#	print("Sometimes read-only, sometimes not read-only: {!r}".format(v))
			if not read_only or (write_only or read_write):
				noro = True
		if noro:
			v = v.split("\n")
			v = [x[x.find("D18"):].split("_")[0] for x in v if x.find("D18") != -1]
			v = ";".join(v)
			print(nice_name, v)
